### ISSUE TITLE
Add debian requirements handling

### ISSUE THREAD

**Issue by rixx** [pretalx/ansible-pretalx#1]
Python 3.6 under Debian is … tricky to say the least.

**Comment by vladionescu** [comment]
Switching system Python default to 3.7 fixes this, at least on Debian 10. It's hard to find a 3.6 package anymore and 3.7 comes standard. Pretalx seems to run just fine on 3.7. I have a PR incoming with this change.

Testing a clean install with my changes now. If it looks good I'll send the PR.

**Comment by rixx** [comment]
Yeah, 3.7 is fine, this issue is from a time when 3.7 was not out yet (or at least no Debian support on the horizon).
