### ISSUE TITLE
Make path to letsencrypt configurable

### ISSUE THREAD

**Issue by informancer** [pretalx/ansible-pretalx#15]
When using python-certbot 0.31.0-1 on Debian buster, the root path to the certificates is `/etc/letsencrypt/live/` instead of `/etc/ssl/letsencrypt/certs/`as expected in the nginx template, thus creating an error when restarting nginx.

**Comment by rixx** [comment]
I've been considering removing anything to do with nginx from the role, but I'd definitely consider merging a PR that adds this variable :)

**Comment by informancer** [comment]
Will do, just not right now.
