### ISSUE TITLE
Python3.7 dependency incompatible with Debian 11

### ISSUE THREAD

**Issue by vladionescu** [pretalx/ansible-pretalx#17]
Enforcing Python 3.7 doesn't seem to be necessary for Pretalx to start and run, Python 3.9 works just fine.

Python 3.7 is only available in Debian 10, the latest Debian 11 only ships 3.9.

Applying the following diff seems to work without side effects, making it so this role asks for latest Python 3.x instead of a specific version.

```diff
diff --git a/defaults/main.yml b/defaults/main.yml
index 918446e..616c352 100644
--- a/defaults/main.yml
+++ b/defaults/main.yml
@@ -1,7 +1,7 @@
 ---
 pretalx_instance_identifier: "event"  # used if you have more than one instance on your server
 
-pretalx_system_python_version: "3.7"
+pretalx_system_python_version: "3"
 
 pretalx_database_backend: postgresql
 pretalx_database_name: pretalx{{ pretalx_instance_identifier }}
diff --git a/tasks/requirements_debian.yml b/tasks/requirements_debian.yml
index f1895f6..df3e51d 100644
--- a/tasks/requirements_debian.yml
+++ b/tasks/requirements_debian.yml
@@ -6,15 +6,15 @@
   tags:
     - pretalx
 
-- name: Install Python 3.7
+- name: Install Python 3
   apt:
     name:
-      - python3.7
-      - python3.7-dev
+      - python3
+      - python3-dev
       - python3-pip
       - python3-wheel
     state: latest
-    default_release: buster
   tags:
     - pretalx
```

**Comment by rixx** [comment]
I was fairly sure that `pretalx_system_version` is required to be a dotted version for inclusion in some paths, unless Debian puts locally installed packages in a less-specific location than I'm used to.

That said, the Debian part of this role is entirely community-maintained, so feel free to open a PR with your changes, as long as you've tested them – and thank you for adding this information!
