### ISSUE TITLE
bump default python to 3.10

### ISSUE THREAD

**Issue by biancarosa** [pretalx/ansible-pretalx#22]
Heya!

We can already bump the default to python3.10 - would you be interested in a PR with this?

**Comment by rixx** [comment]
Sure!

**Comment by MikkCZ** [comment]
I am wondering, is there any reason not to set the default of `pretalx_system_python_version: "3"` instead of a specific minor version like `"3.9"` or now proposed `"3.10"`?

**Comment by MikkCZ** [comment]
Actually, now I see this variable is necessary not only during `python` invocation, but also for paths in the systemd files.
